name: 'In*Situ Architecture'
favicon: null
layout_spectrum: 0.28325
typography_spectrum: 0.90357
title: 'In*Situ Architecture'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ebfffe'
    - '#59443f'
    - '#a62625'
    - '#bcb6c8'
    - '#211c1e'
  brandStrength: 0.25
  lightness: 0.3551787850446999
  saturation: 0.5
  rhythmicContrast: 0.6210624445229769
purpose: []
