name: 'In*Situ Architecture'
favicon: null
layout_spectrum: 1
typography_spectrum: 0.91501
title: 'In*Situ Architecture'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#404040'
    - '#ed1d25'
    - '#1d1d1d'
    - '#540a0c'
  brandStrength: 0.75
  lightness: 0.3125
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
